### ISSUE TITLE
Google Analytics cannot be disabled as claimed in the Readme

### ISSUE THREAD

**Issue by T-vK** [nhn/tui.code-snippet#22]
## Version
1.5.0

## Development Environment
Windows, Linux, Chrome, Firefox
Running the image editor using the latest releases of the color picker, image editor and code snippet.

## Current Behavior
The code snippet script is sending usage statistics to www.google-analytics.com
Setting `tui.usageStatistics = false` right before or after loading the script does not prevent that. 

Here is an example: https://fiddle.sencha.com/#view/editor&fiddle/2p07
You can see that it silently sends a request to `https://www.google-analytics.com/collect?v=1&t=event&tid=UA-115377265-9&cid=fiddle.sencha.com&dp=fiddle.sencha.com&dh=color-picker` if you inspect the network traffic.

## Expected Behavior
Setting `tui.usageStatistics` to `false` should reliably disable Google Analytics completely! This is absolutely crucial as it is **illegal** to collect such data without user consent in the EU and other countries.

**Comment by DanielQuero** [comment]
I have the same problem, apparently is not possible to disable the 'usageStatistics' as they said id the Docs. 

Like you said, it's ilegal in EU without usent consent. I hope they do something about that or improve the Docs to explain the correct way of disable the statistics.

**Comment by juanmiSignlab** [comment]
I have the same problem too.

**Comment by jung-han** [comment]
@T-vK @DanielQuero @juanmiSignlab 
Sorry for late. It caused that Image-Editor bundling issue.
It will be release soon. Please check the image-editor release note.(https://github.com/nhnent/tui.image-editor/releases)

**Comment by T-vK** [comment]
There still haven't been any commits in this Project for months and #23 was never accepted. I also checked the release page you linked, but there is no mention of a fix for this issue.

**Comment by jung-han** [comment]
@T-vK use Image-Editor v3.5.1
