### ISSUE TITLE
Build failed since webpack cannot find entry module

### ISSUE THREAD

**Issue by keedi** [nhn/tui.code-snippet#35]
## Version

v2.0.0

## Development Environment

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
$ node --version
v12.13.0
```

## Current Behavior

```js
[askdna@bebop-i5 tui.code-snippet master]$ git checkout v2.0.0
Note: switching to 'v2.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at fb0d71e Merge branch 'master' into production
[askdna@bebop-i5 tui.code-snippet (v2.0.0)]$ yarn install
yarn install v1.19.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 2.28s.
[askdna@bebop-i5 tui.code-snippet (v2.0.0)]$ npm run bundle

> tui-code-snippet@2.0.0 bundle /tmp/askdna/tui.code-snippet
> webpack & webpack --production

Hash: 451d148498b0218ba862
Version: webpack 1.15.0
Time: 13ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/js/index.js in /tmp/askdna/tui.code-snippet
Hash: 4cc2c8905467c5a2eeb0
Version: webpack 1.15.0
Time: 13ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/js/index.js in /tmp/askdna/tui.code-snippet
[askdna@bebop-i5 tui.code-snippet (v2.0.0)]$
```

## Expected Behavior

I expect `npm run bundle` generates built result, but the build fails. Since d04b9cb4bb29c0f30ed9c9aab2d60e884e2acd75 commit removes the webpack entry file which is `index.js`, then webpack complains about that.

**Comment by dotaitch** [comment]
Hello, @keedi 

Since v2.0.0, tui-code-snippet does not support bundling to provide importing only functions that users need. To use one bundle file for tui-code-snippet, you should use the lower version such as v1.5.2. 

To know how to migrate v2.0.0, please refer to [v2.0 Migration Guide](https://github.com/nhn/tui.code-snippet/blob/v2.0.0/docs/v2.0-migration-guide.md).
To know how to use the v2.0.0 of tui-code-snippet, please refer to [Getting Started](https://github.com/nhn/tui.code-snippet/blob/v2.0.0/docs/getting-started.md).

If you have other questions, please let me know.

**Comment by keedi** [comment]
Hi, thanks for fast reply.

I was curious since there was still a command `npm run bundle` for webpack bundling in `package.json` and was confused because the [latest source](https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js) from TOAST CDN is still bundled. After your comment, I checked the CDN file and now I see its version is just v1.5.2.

Now I understand the way of new changes about v2.0.0. Thanks.

**Comment by keedi** [comment]
BTW, v1.5.2 version is failed to build via run `npm run bundle` due to eslint error.

Attached logs:
```bash
$ git checkout v1.5.2
HEAD is now at 2a459f7 1.5.2
$ npx webpack
Hash: b194adbeae73abe60c2f
Version: webpack 1.15.0
Time: 1086ms
              Asset    Size  Chunks             Chunk Names
tui-code-snippet.js  120 kB       0  [emitted]  main
    + 21 hidden modules

WARNING in ./src/js/type.js

/mnt/3t/workspace/gitlab/skyloader/tui/tui.code-snippet/src/js/type.js
  256:1  warning  Function 'isEmpty' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)


WARNING in ./src/js/array.js

/mnt/3t/workspace/gitlab/skyloader/tui/tui.code-snippet/src/js/array.js
  106:15  warning  Function has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)


ERROR in ./src/js/object.js

/mnt/3t/workspace/gitlab/skyloader/tui/tui.code-snippet/src/js/object.js
  192:16  error  Unnecessary 'else' after 'return'                                                                           no-else-return
  199:5   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
  202:16  error  Unnecessary 'else' after 'return'                                                                           no-else-return

✖ 3 problems (3 errors, 0 warnings)
  2 errors, 0 warnings potentially fixable with the `--fix` option.

```

**Comment by dotaitch** [comment]
Hello, @keedi 

1. The reason why CDN@latest is still v1.5.2 is for other CDN@latest users. If we had not provided CDN@latest when tui-code-snippet was updated to v2.0, other projects using CDN@latest would have had issues. So, we decided to maintain the latest tag for v1.5.2, the latest version of CDN, for a while. CDN@latest will be deprecated in the future.

2. I agree that `npm run bundle` confuses users and it should be deleted. I will delete this command in the next release.

3. 2 warnings are known issues and they do not have an influence on the bundling process. However, 3 errors from the `src/js/object.js` are weird and I cannot reproduce the same errors. Can you compare your codes and the below codes?
    * `no-else-return` error, but this line does not have an `else` statement. [[object.js#L192]](https://github.com/nhn/tui.code-snippet/blob/v1.5.2/src/js/object.js#L192)
    * `guard-for-in` error, but it has an `if` statement to filter properties. [[object.js#L199]](https://github.com/nhn/tui.code-snippet/blob/v1.5.2/src/js/object.js#L199)
    * `no-else-return` error, but this line does not have an `else` statement. [[object.js#L202]](https://github.com/nhn/tui.code-snippet/blob/v1.5.2/src/js/object.js#L202)

**Comment by keedi** [comment]
I've just found that if `node_modules` are installed via `yarn` then those errors are occurred. After your comment I removed `node_modules` then install using `npm` then it just works w/ 2 warnings and w/o errors.

**Comment by dotaitch** [comment]
We recommend using `npm` rather than `yarn`.

In v2.1.0, we decided to add the entry file to bundle, so `npm run bundle` is not removed. If you need a bundle file of v2.1.0, please refer to [this](https://github.com/nhn/tui.code-snippet/tree/v2.1.0#bundle).
